package jdbc;
// Generated 25-feb-2018 13:38:06 by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private int ref;
	private String nombre;
	private BigDecimal precio;
	private Integer existencias;
	private Set<Ventas> ventases = new HashSet<Ventas>(0);

	public Productos() {
	}

	public Productos(int ref, String nombre) {
		this.ref = ref;
		this.nombre = nombre;
	}

	public Productos(int ref, String nombre, BigDecimal precio, Integer existencias, Set<Ventas> ventases) {
		this.ref = ref;
		this.nombre = nombre;
		this.precio = precio;
		this.existencias = existencias;
		this.ventases = ventases;
	}
	
	



	public int getRef() {
		return this.ref;
	}

	public void setRef(int ref) {
		this.ref = ref;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public Integer getExistencias() {
		return this.existencias;
	}

	public void setExistencias(Integer existencias) {
		this.existencias = existencias;
	}

	public Set<Ventas> getVentases() {
		return this.ventases;
	}

	public void setVentases(Set<Ventas> ventases) {
		this.ventases = ventases;
	}

}
